services:
  # Redis
  redis:
    image: redis:7.2
    container_name: linces-hub-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # License Hub
  web:
    build: .
    container_name: license-hub-web
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  redis-data:
